apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-api
  namespace: gnosis-api
  labels:
    app: gnosis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnosis-api
  template:
    metadata:
      labels:
        app: gnosis-api
    spec:
      imagePullSecrets:
        - name: gitea-registry-creds
      containers:
        - name: gnosis-api
          image: git.thespears.net/kspears/gnosis-api:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: gnosis-api-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
