apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gnosis-api-secret
  namespace: gnosis-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: gnosis-api-secret
    creationPolicy: Owner
  data:
    - secretKey: GNOSIS_API_KEY_SALT
      remoteRef:
        key: gnosis-api
        property: api-key-salt
