apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gnosis-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.gnosistool.com
      secretName: gnosis-api-tls
  rules:
    - host: api.gnosistool.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gnosis-api
                port:
                  number: 80
