apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gnosis-api-rate-limit
  namespace: gnosis-api
spec:
  rateLimit:
    average: 10
    burst: 20
    period: 1s
    sourceCriterion:
      ipStrategy:
        depth: 1
