apiVersion: v1
kind: Service
metadata:
  name: gnosis-api
  namespace: gnosis-api
  labels:
    app: gnosis-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: gnosis-api
